import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case finnish = "fi"

    var id: String { rawValue }

    var label: String {
        switch self {
        case .english:
            return "English"
        case .finnish:
            return "Suomi"
        }
    }
}

enum L10n {
    private static let translations: [AppLanguage: [String: String]] = [
        .english: [
            "settings": "settings",
            "done": "done",
            "timer": "timer",
            "adjust_flow": "adjust your flow first",
            "focus_duration": "focus duration",
            "short_break": "short break",
            "sessions_before_long_break": "sessions before long break",
            "long_break": "long break",
            "auto_start_next_session": "auto-start next session",
            "account_profile": "account profile",
            "name_email_plan": "name, email and plan",
            "your_name": "your name",
            "email": "email",
            "weekly_summary_email": "weekly summary email",
            "wellwell_pro_active": "wellwell pro active",
            "free_plan": "free plan",
            "thanks_supporting": "thanks for supporting wellwell",
            "upgrade_more_personalization": "upgrade for more personalization",
            "upgrade_to_pro": "upgrade to pro",
            "app_settings": "app settings",
            "language_sounds_look": "language, sounds and look",
            "language": "language",
            "sound": "sound",
            "notifications": "notifications",
            "cloud_color": "cloud color",
            "min": "min",
            "stats": "stats",
            "open_main_window": "open main window",
            "reset_timer": "reset timer",
            "quit_wellwell": "quit wellwell",
            "start_focus": "start focus",
            "take_earned_break": "take an earned break",
            "continue_session_risk": "continue session at your own risk",
            "skip_break": "skip break",
            "sorry_late": "sorry i'm late but good to go again!",
            "nice_work": "nice work ✨",
            "today_sessions_minutes": "today: %d sessions • %d min",
            "status_you_showed_up": "you showed up today",
            "status_ready_when_you_are": "ready when you are",
            "status_work_in_progress": "work in progress",
            "status_time_for_break": "time for a %@",
            "status_break_session": "%@ session",
            "status_good_to_go_again": "good to go again?",
            "status_gentle_break_reminder": "gentle break reminder",
            "status_restart_gently": "restart gently",
            "bubble_ready": "i’m ready when you are",
            "bubble_one_block_enough": "one focused block is enough for today.",
            "bubble_keep_up": "keep up! you're doing great!",
            "bubble_break_time": "whoa! it's break-time!",
            "bubble_come_back": "come back, i miss you already.",
            "header_lovely_day": "what a lovely day to work!",
            "streak_days": "%d-day streak",
            "today_count": "%d today",
            "welcome_back": "welcome back",
            "hi_name": "hi, %@",
            "lets_begin": "let’s begin",
            "go": "go!",
            "pause": "pause",
            "status_nice_work_next": "nice work. %@ next",
            "status_then_we_go_again": "%@, then we can go again",
            "status_ready_continue": "ready to continue?",
            "status_short_break_counts": "a short break still counts",
            "bubble_hey_ready": "hey, i’m ready when you are",
            "bubble_quietly_proud": "you showed up today. quietly proud of you.",
            "bubble_short_session_counts": "it’s okay. a short session still counts.",
            "bubble_another_round": "ready for another gentle round?",
            "bubble_nice_work_counted": "nice work. that counted.",
            "completion_sessions_today": "you’ve done %d session%@ today.",
            "completion_focus_duration": "that’s %@ of focus.",
            "completion_streak": "you’re on a %d-day streak.",
            "take_a_breath": "take a breath",
            "streak_label": "streak: %d day%@",
            "reaction_sleepy": "shh... warming up ☁️",
            "reaction_happy": "yay, you’re on a roll!",
            "reaction_excited": "woah, amazing focus!",
            "reaction_golden": "golden cloud sighting ✨",
            "start": "start",
            "focus_short": "focus",
            "break_short": "break",
            "sessions_short": "sessions",
            "progress": "progress: %@",
            "close_pro_settings": "close pro settings",
            "pro_title": "Wellwell Pro",
            "pro_customize": "Customize your session lengths to match your flow.",
            "close_paywall": "close paywall",
            "unlock_pro": "unlock wellwell pro ☁️",
            "pro_pitch": "Your cloud buddy wants to help you focus your way. Unlock Pro for custom session lengths forever.",
            "adopt_cloud_pro": "adopt cloud pro",
            "restore_purchase": "restore purchase",
            "menu_focus_time": "focus %@",
            "menu_break_question": "break?",
            "menu_break_time": "break %@",
            "menu_work_question": "work?",
            "menu_break_alert": "break!",
            "menu_work_alert": "work!",
            "today_minutes": "%d min today",
            "today_hours_minutes": "%d h %02d min today",
            "milestone_consistency": "nice consistency",
            "milestone_focus_streak": "strong focus streak",
            "milestone_locked_in": "you’re locked in",
            "milestone_elite": "elite discipline",
            "focus_command_menu": "Focus",
            "start_focus_session": "Start Focus Session",
            "notification_focus_complete_title": "Focus session complete",
            "notification_focus_complete_body": "Great work! Start your break when you're ready.",
            "notification_break_finished_title": "Break finished",
            "notification_break_finished_body": "You're recharged—resume work when you're ready.",
            "notification_break_waiting_title": "Break still waiting",
            "notification_break_waiting_body": "You haven't started your break yet. Take a quick reset.",
            "notification_resume_work_title": "Time to resume work",
            "notification_resume_work_body": "You haven't resumed work yet. Jump back in when ready."
        ],
        .finnish: [
            "settings": "asetukset",
            "done": "valmis",
            "timer": "ajastin",
            "adjust_flow": "säädä rytmi itsellesi",
            "focus_duration": "fokusjakso",
            "short_break": "lyhyt tauko",
            "sessions_before_long_break": "jaksoja ennen pitkää taukoa",
            "long_break": "pitkä tauko",
            "auto_start_next_session": "käynnistä seuraava jakso automaattisesti",
            "account_profile": "tili",
            "name_email_plan": "nimi, sähköposti ja tilaus",
            "your_name": "nimesi",
            "email": "sähköposti",
            "weekly_summary_email": "viikkoyhteenveto sähköpostiin",
            "wellwell_pro_active": "wellwell pro käytössä",
            "free_plan": "ilmainen versio",
            "thanks_supporting": "kiitos, että tuet wellwelliä",
            "upgrade_more_personalization": "päivitä saadaksesi enemmän personointia",
            "upgrade_to_pro": "päivitä pro-versioon",
            "app_settings": "sovelluksen asetukset",
            "language_sounds_look": "kieli, äänet ja ulkoasu",
            "language": "kieli",
            "sound": "äänet",
            "notifications": "ilmoitukset",
            "cloud_color": "pilven väri",
            "min": "min",
            "stats": "tilastot",
            "open_main_window": "avaa pääikkuna",
            "reset_timer": "nollaa ajastin",
            "quit_wellwell": "sulje wellwell",
            "start_focus": "aloita fokus",
            "take_earned_break": "pidä ansaittu tauko",
            "continue_session_risk": "jatka omalla vastuulla",
            "skip_break": "ohita tauko",
            "sorry_late": "myöhästyin, mutta jatketaan!",
            "nice_work": "hienoa työtä ✨",
            "today_sessions_minutes": "tänään: %d sessiota • %d min",
            "status_you_showed_up": "teit sen tänään",
            "status_ready_when_you_are": "valmis kun sinä olet",
            "status_work_in_progress": "työ käynnissä",
            "status_time_for_break": "aika %@",
            "status_break_session": "%@",
            "status_good_to_go_again": "jatketaanko taas?",
            "status_gentle_break_reminder": "lempeä taukomuistutus",
            "status_restart_gently": "aloita rauhassa uudelleen",
            "bubble_ready": "olen valmis kun sinä olet",
            "bubble_one_block_enough": "yksi fokusjakso riittää tältä päivältä.",
            "bubble_keep_up": "hyvin menee, jatka samaan malliin!",
            "bubble_break_time": "wohoo! tauon aika!",
            "bubble_come_back": "tule takaisin, kaipaan jo.",
            "header_lovely_day": "ihanan hyvä päivä tehdä töitä!",
            "streak_days": "%d päivän putki",
            "today_count": "%d tänään",
            "welcome_back": "tervetuloa takaisin",
            "hi_name": "hei, %@",
            "lets_begin": "aloitetaan",
            "go": "mennään!",
            "pause": "tauko",
            "status_nice_work_next": "hienoa työtä. seuraavaksi %@",
            "status_then_we_go_again": "%@, sitten jatketaan taas",
            "status_ready_continue": "jatketaanko?",
            "status_short_break_counts": "lyhytkin tauko riittää",
            "bubble_hey_ready": "hei, olen valmis kun sinä olet",
            "bubble_quietly_proud": "teit sen tänään. olen hiljaa ylpeä sinusta.",
            "bubble_short_session_counts": "ei hätää. lyhytkin sessio lasketaan.",
            "bubble_another_round": "vielä yksi lempeä kierros?",
            "bubble_nice_work_counted": "hienoa työtä. se laskettiin.",
            "completion_sessions_today": "olet tehnyt tänään %d session%@.",
            "completion_focus_duration": "se on %@ fokusta.",
            "completion_streak": "sinulla on %d päivän putki.",
            "take_a_breath": "hengitä hetki",
            "streak_label": "putki: %d päivä%@",
            "reaction_sleepy": "shh... lämmitellään ☁️",
            "reaction_happy": "jee, hyvä flow päällä!",
            "reaction_excited": "wau, mahtava fokus!",
            "reaction_golden": "kultainen pilvihavainto ✨",
            "start": "aloita",
            "focus_short": "fokus",
            "break_short": "tauko",
            "sessions_short": "sessiot",
            "progress": "edistyminen: %@",
            "close_pro_settings": "sulje pro-asetukset",
            "pro_title": "Wellwell Pro",
            "pro_customize": "Muokkaa sessioiden pituudet omaan rytmiisi.",
            "close_paywall": "sulje maksuseinä",
            "unlock_pro": "avaa wellwell pro ☁️",
            "pro_pitch": "Pilvikaverisi haluaa auttaa sinua keskittymään omalla tavallasi. Avaa Pro ja saat mukautetut session pituudet pysyvästi.",
            "adopt_cloud_pro": "ota cloud pro",
            "restore_purchase": "palauta ostos",
            "menu_focus_time": "fokus %@",
            "menu_break_question": "tauko?",
            "menu_break_time": "tauko %@",
            "menu_work_question": "töihin?",
            "menu_break_alert": "tauko!",
            "menu_work_alert": "työ!",
            "today_minutes": "%d min tänään",
            "today_hours_minutes": "%d h %02d min tänään",
            "milestone_consistency": "hienoa tasaisuutta",
            "milestone_focus_streak": "vahva fokusputki",
            "milestone_locked_in": "olet todella flow’ssa",
            "milestone_elite": "eliittitason kurinalaisuus",
            "focus_command_menu": "Fokus",
            "start_focus_session": "Aloita fokusjakso",
            "notification_focus_complete_title": "Fokusjakso valmis",
            "notification_focus_complete_body": "Hienoa työtä! Aloita tauko kun olet valmis.",
            "notification_break_finished_title": "Tauko päättyi",
            "notification_break_finished_body": "Olet latautunut — jatka töitä kun olet valmis.",
            "notification_break_waiting_title": "Tauko odottaa yhä",
            "notification_break_waiting_body": "Et ole vielä aloittanut taukoa. Käy pikaisella palautuksella.",
            "notification_resume_work_title": "Aika palata töihin",
            "notification_resume_work_body": "Et ole vielä jatkanut työtä. Hyppää takaisin kun olet valmis."
        ]
    ]

    static var currentLanguage: AppLanguage {
        let stored = UserDefaults.standard.string(forKey: "preferredLanguage") ?? AppLanguage.english.rawValue
        return AppLanguage(rawValue: stored) ?? .english
    }

    static func tr(_ key: String) -> String {
        translations[currentLanguage]?[key] ?? translations[.english]?[key] ?? key
    }

    static func tr(_ key: String, _ args: CVarArg...) -> String {
        String(format: tr(key), locale: Locale(identifier: currentLanguage.rawValue), arguments: args)
    }
}
